In [2]:
import pandas as pd
import lxml
import requests
import yfinance as yf
from io import StringIO

In [3]:
url= "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [4]:
response=requests.get(url, headers=headers)

sp500=pd.read_html(StringIO(response.text))[0]
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [5]:
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [6]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [7]:
# list of ticker symbols for download (Needs to be done for S&P 500)
tickerStrings = sp500['Symbol'].tolist()

In [8]:
df = yf.download(tickerStrings, group_by='Ticker', period='1d')

[*********************100%***********************]  503 of 503 completed

In [9]:
df

Ticker            INTU                                                \
Price             Open        High         Low       Close    Volume
Date
2021-06-21  461.571007  465.382128  456.560456  462.267456   1073600
2021-06-22  461.696776  464.047282  459.578411  461.938599   1480600
2021-06-23  461.938721  466.426958  461.938721  462.935028   1218800
2021-06-24  466.233476  470.344456  464.589072  466.833191   1088500
2021-06-25  465.256364  474.155436  461.396890  470.189545   1494500
...                ...         ...         ...         ...       ...
2026-06-12  276.019989  276.859985  268.010010  276.730011   5153700
2026-06-15  277.760010  287.690002  276.209991  281.769989   5098600
2026-06-16  282.200012  284.799988  275.380005  280.989990   4813900
2026-06-17  279.850006  285.890015  268.480011  269.079987   4709900
2026-06-18  261.000000  269.869995  259.230011  267.000000  10059100

Ticker             SJM                                               ...  \
Price             Open        High         Low       Close   Volume  ...
Date                                                                 ...
2021-06-21  110.054744  110.896914  109.962117  110.425301   673200  ...
2021-06-22  110.728474  111.200087  109.793665  109.919998   848100  ...
2021-06-23  109.482071  110.054741  108.690430  108.690430   612000  ...
2021-06-24  108.277794  109.103117  107.166123  108.277794   574800  ...
2021-06-25  107.881949  109.305205  107.780887  108.993607   786100  ...
...                ...         ...         ...         ...      ...  ...
2026-06-12  117.739998  117.739998  114.790001  116.489998  1600600  ...
2026-06-15  114.739998  116.019997  113.500000  115.940002  1190200  ...
2026-06-16  115.900002  116.919998  115.169998  115.989998   936600  ...
2026-06-17  114.989998  116.209999  112.589996  112.959999  1138600  ...
2026-06-18  112.610001  114.160004  110.629997  110.860001  2176200  ...

Ticker              LLY                                                   \
Price              Open         High          Low        Close    Volume
Date
2021-06-21   209.002990   213.457776   208.029992   212.408463   3671300
2021-06-22   212.370300   213.305134   210.347989   211.235138   1658800
2021-06-23   211.950582   211.998281   206.999756   207.095154   2419600
2021-06-24   224.093959   228.338883   219.801337   222.233826  12290500
2021-06-25   222.376916   222.729875   218.818813   219.610565   6992200
...                 ...          ...          ...          ...       ...
2026-06-12  1165.000000  1169.989990  1132.810059  1133.000000   2438400
2026-06-15  1134.000000  1137.489990  1112.010010  1129.349976   3167200
2026-06-16  1138.819946  1146.689941  1115.500000  1122.500000   2260700
2026-06-17  1116.699951  1121.489990  1104.900024  1112.000000   2383300
2026-06-18  1120.489990  1122.329956  1088.660034  1098.569946   4470500

Ticker             TPR
Price             Open        High         Low       Close   Volume
Date
2021-06-21   36.392896   37.244964   36.322621   37.034142  2575300
2021-06-22   36.919946   37.306453   36.366545   37.157120  1698300
2021-06-23   37.262527   37.824718   37.174687   37.420643  2060900
2021-06-24   37.728083   38.070666   37.262519   37.798355  1724400
2021-06-25   38.272711   38.993014   38.053106   38.193653  7019500
...                ...         ...         ...         ...      ...
2026-06-12  149.830002  150.550003  146.070007  147.419998  2032000
2026-06-15  150.130005  156.740005  149.979996  150.990005  3558600
2026-06-16  151.500000  153.669998  149.089996  149.389999  2343200
2026-06-17  149.240005  152.660004  145.720001  145.869995  2246500
2026-06-18  148.210007  149.919998  143.009995  143.500000  5860900

[1255 rows x 2515 columns]

In [10]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2021-06-21,INTU,461.571007,465.382128,456.560456,462.267456,1073600.0
1,2021-06-21,SJM,110.054744,110.896914,109.962117,110.425301,673200.0
2,2021-06-21,EQT,18.111447,19.082872,18.111447,19.064190,4111500.0
3,2021-06-21,CBOE,106.958440,112.914692,106.817295,111.070419,1065500.0
4,2021-06-21,DELL,45.767723,46.192009,45.689322,46.118221,3652418.0
...,...,...,...,...,...,...,...
631260,2026-06-18,DXCM,72.610001,73.690002,71.599998,72.470001,8571700.0
631261,2026-06-18,NUE,252.949997,254.110001,242.050003,243.830002,5190800.0
631262,2026-06-18,FITB,53.090000,53.209999,52.560001,52.740002,11882300.0
631263,2026-06-18,LLY,1120.489990,1122.329956,1088.660034,1098.569946,4470500.0
631264,2026-06-18,TPR,148.210007,149.919998,143.009995,143.500000,5860900.0

In [11]:
downloaded_tickers=set(df["Ticker"].unique())

In [12]:
missing = set(tickerStrings) - downloaded_tickers

missing

set()

In [13]:
len(downloaded_tickers)

503

In [14]:
row_counts = df.groupby("Ticker").size()
print(row_counts.sort_values())

Ticker
A       1255
NWS     1255
NVR     1255
NVDA    1255
NUE     1255
        ...
ELV     1255
EL      1255
EIX     1255
ETR     1255
ZTS     1255
Length: 503, dtype: int64

In [15]:
for ticker in ["FRT", "PHM", "SYY"]:
    count = (df["Ticker"] == ticker).sum()
    print(f"{ticker}: {count} rows")

FRT: 1255 rows
PHM: 1255 rows
SYY: 1255 rows

In [17]:
df.columns.name = None
df

,Date,Ticker,Open,High,Low,Close,Volume
0,2021-06-21,INTU,461.571007,465.382128,456.560456,462.267456,1073600.0
1,2021-06-21,SJM,110.054744,110.896914,109.962117,110.425301,673200.0
2,2021-06-21,EQT,18.111447,19.082872,18.111447,19.064190,4111500.0
3,2021-06-21,CBOE,106.958440,112.914692,106.817295,111.070419,1065500.0
4,2021-06-21,DELL,45.767723,46.192009,45.689322,46.118221,3652418.0
...,...,...,...,...,...,...,...
631260,2026-06-18,DXCM,72.610001,73.690002,71.599998,72.470001,8571700.0
631261,2026-06-18,NUE,252.949997,254.110001,242.050003,243.830002,5190800.0
631262,2026-06-18,FITB,53.090000,53.209999,52.560001,52.740002,11882300.0
631263,2026-06-18,LLY,1120.489990,1122.329956,1088.660034,1098.569946,4470500.0
631264,2026-06-18,TPR,148.210007,149.919998,143.009995,143.500000,5860900.0

In [18]:
test = yf.download(["BRK-B","BF-B"], period="5d")
print(test)

[*********************100%***********************]  2 of 2 completed

Price           Close                   High                    Low  \
Ticker           BF-B       BRK-B       BF-B       BRK-B       BF-B
Date
2026-06-12  27.010000  489.250000  27.080000  489.989990  26.450001
2026-06-15  26.940001  495.519989  27.360001  497.109985  26.879999
2026-06-16  26.610001  494.950012  27.230000  499.790009  26.469999
2026-06-17  25.510000  491.279999  26.580000  494.769989  25.270000
2026-06-18  26.639999  489.459991  26.850000  493.570007  25.610001

Price                        Open               Volume
Ticker           BRK-B       BF-B       BRK-B     BF-B    BRK-B
Date
2026-06-12  484.510010  26.709999  486.670013  2186600  4591300
2026-06-15  487.559998  26.940001  487.559998  2981100  6253600
2026-06-16  492.429993  27.030001  497.000000  2147000  4345900
2026-06-17  487.899994  26.480000  493.239990  3038200  5412000
2026-06-18  485.769989  25.879999  492.750000  7148100  8882300

In [19]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [20]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [21]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [22]:
test = yf.download("FDS", period="5d")
print(test)

test2 = yf.download("MS", period="5d")
print(test2)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker             FDS         FDS         FDS         FDS      FDS
Date
2026-06-12  241.160004  243.240005  231.149994  237.000000  2059000
2026-06-15  235.860001  247.080002  234.660004  238.740005   579200
2026-06-16  237.559998  241.740005  235.009995  237.770004   562600
2026-06-17  228.300003  240.570007  228.300003  234.860001   648900
2026-06-18  221.289993  223.990005  216.559998  218.679993  1732900

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker              MS          MS          MS          MS        MS
Date
2026-06-12  214.039993  217.619995  212.660004  215.050003   4694300
2026-06-15  217.979996  220.600006  216.850006  218.759995   5862500
2026-06-16  220.830002  222.300003  218.589996  220.509995   5091700
2026-06-17  224.960007  228.070007  221.360001  222.110001   8689700
2026-06-18  223.169998  230.470001  222.889999  229.089996  11933200

In [23]:
df.to_csv('backfill_data_2206.csv')

In [24]:
ohlcv_cols = ["Open", "High", "Low", "Close", "Volume"]

null_summary = (
    df[df["Ticker"].isin(["FRT", "PHM", "SYY", "GOOG", "BF-B"])]
    .groupby("Ticker")[ohlcv_cols]
    .apply(lambda x: x.isna().sum())
)
print(null_summary)

        Open  High  Low  Close  Volume
Ticker
BF-B       0     0    0      0       0
FRT        0     0    0      0       0
GOOG       0     0    0      0       0
PHM        0     0    0      0       0
SYY        0     0    0      0       0

In [25]:
null_counts_by_ticker = (
    df.groupby("Ticker")[ohlcv_cols]
    .apply(lambda x: x.isna().sum().sum())  # total nulls across all OHLCV cols, per ticker
    .sort_values(ascending=False)
)

print(null_counts_by_ticker.head(10))

Ticker
FDXF    6190
Q       5465
SNDK    4585
GEV     3480
SOLV    3475
VLTO    2880
KVUE    2355
GEHC    1880
CEG      735
HOOD     135
dtype: int64