In [1]:
import pandas as pd
import lxml
import requests
import yfinance as yf
from io import StringIO

In [2]:
url= "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [3]:
response=requests.get(url, headers=headers)

sp500=pd.read_html(StringIO(response.text))[0]
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [4]:
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [5]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [6]:
# list of ticker symbols for download (Needs to be done for S&P 500)
tickerStrings = sp500['Symbol'].tolist()

In [7]:
df = yf.download(tickerStrings, group_by='Ticker', period='5y')

[*********             19%                       ]  95 of 503 completed$FRT: possibly delisted; no price data found  (period=5y)
[*******************   39%                       ]  197 of 503 completed$PHM: possibly delisted; no price data found  (period=5y)
[**********************86%****************       ]  432 of 503 completed$SYY: possibly delisted; no price data found  (period=5y)
[*********************100%***********************]  503 of 503 completed

3 Failed downloads:
['FRT', 'PHM', 'SYY']: possibly delisted; no price data found  (period=5y)

In [8]:
df

Ticker            VRSN                                               \
Price             Open        High         Low       Close   Volume
Date
2021-06-21  220.366970  222.366633  218.574160  221.381577   511300
2021-06-22  221.618002  223.735882  220.938311  223.460068   427000
2021-06-23  223.804785  224.090460  221.775571  222.928085   427100
2021-06-24  223.775258  226.503868  223.765413  226.001480   549400
2021-06-25  226.612227  226.651623  222.662141  224.326889  2239300
...                ...         ...         ...         ...      ...
2026-06-12  280.019989  281.739990  278.609985  279.890015   513900
2026-06-15  279.209991  280.489990  269.420013  272.959991   778100
2026-06-16  273.399994  276.350006  272.220001  273.869995   554700
2026-06-17  270.450012  271.190002  263.799988  264.920013   612700
2026-06-18  267.440002  267.989990  262.130005  264.640015  1820900

Ticker           BF-B                                            ...  \
Price            Open       High        Low      Close   Volume  ...
Date                                                             ...
2021-06-21  65.870773  66.372575  65.548184  66.336731   783000  ...
2021-06-22  66.506987  66.506987  66.005185  66.032066   675700  ...
2021-06-23  65.897643  66.166462  65.324153  65.342072   688400  ...
2021-06-24  65.610908  66.480106  65.333126  66.372574   751600  ...
2021-06-25  66.256086  67.385141  65.915572  67.304497  2012400  ...
...               ...        ...        ...        ...      ...  ...
2026-06-12  26.709999  27.080000  26.450001  27.010000  2186600  ...
2026-06-15  26.940001  27.360001  26.879999  26.940001  2981100  ...
2026-06-16  27.030001  27.230000  26.469999  26.610001  2147000  ...
2026-06-17  26.480000  26.580000  25.270000  25.510000  3038200  ...
2026-06-18  25.879999  26.850000  25.610001  26.639999  7148100  ...

Ticker            EXPE                                               \
Price             Open        High         Low       Close   Volume
Date
2021-06-21  161.358542  166.425695  160.805405  165.862671  2218900
2021-06-22  166.455312  166.860277  163.136478  164.884781  1397200
2021-06-23  164.637843  167.946805  164.213119  166.880035  1243000
2021-06-24  167.848043  168.430826  166.247896  167.966583  1118300
2021-06-25  168.430792  170.663097  166.939283  168.895035  4977100
...                ...         ...         ...         ...      ...
2026-06-12  226.350006  229.740005  220.490005  224.889999  1257400
2026-06-15  229.899994  239.490005  229.229996  236.979996  1675300
2026-06-16  237.089996  246.500000  237.089996  243.559998  1778900
2026-06-17  241.880005  244.360001  238.809998  239.470001  1174300
2026-06-18  242.050003  243.759995  238.850006  240.899994  3024200

Ticker             GM
Price            Open       High        Low      Close    Volume
Date
2021-06-21  57.388141  57.388141  56.494903  56.955929  12276900
2021-06-22  57.186448  57.244074  56.687003  56.898308   8928500
2021-06-23  57.484187  58.041262  57.109604  57.743515  11527900
2021-06-24  58.002850  58.108503  57.397753  57.666687  14445300
2021-06-25  57.906794  58.185331  57.647466  57.916397  14255100
...               ...        ...        ...        ...       ...
2026-06-12  81.720001  82.129997  80.500000  81.500000   4953800
2026-06-15  82.639999  84.959999  82.639999  84.070000   7893300
2026-06-16  84.650002  85.410004  82.220001  82.510002   7894200
2026-06-17  82.500000  83.180000  79.160004  79.580002  11406000
2026-06-18  80.610001  80.949997  78.940002  79.290001  18900900

[1255 rows x 2518 columns]

In [9]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2021-06-21,VRSN,220.366970,222.366633,218.574160,221.381577,511300.0,NaN
1,2021-06-21,BF-B,65.870773,66.372575,65.548184,66.336731,783000.0,NaN
2,2021-06-21,MSI,196.559049,200.433110,195.399663,199.179459,746300.0,NaN
3,2021-06-21,WSM,69.193813,71.281085,69.121053,70.658089,1887400.0,NaN
4,2021-06-21,MET,50.399791,51.361588,50.399791,51.249950,6101100.0,NaN
...,...,...,...,...,...,...,...,...
631260,2026-06-18,COST,962.700012,964.000000,948.309998,951.450012,3742900.0,NaN
631261,2026-06-18,FISV,48.570000,48.950001,47.500000,47.860001,13540200.0,NaN
631262,2026-06-18,EQIX,1104.500000,1114.599976,1088.619995,1092.189941,807800.0,NaN
631263,2026-06-18,EXPE,242.050003,243.759995,238.850006,240.899994,3024200.0,NaN
631264,2026-06-18,GM,80.610001,80.949997,78.940002,79.290001,18900900.0,NaN

In [11]:
downloaded_tickers=set(df["Ticker"].unique())

In [12]:
missing = set(tickerStrings) - downloaded_tickers

missing

set()

In [15]:
len(downloaded_tickers)

503

In [16]:
row_counts = df.groupby("Ticker").size()
print(row_counts.sort_values())

Ticker
A       1255
AAPL    1255
ABBV    1255
ABNB    1255
ABT     1255
        ...
XYZ     1255
YUM     1255
ZBH     1255
ZBRA    1255
ZTS     1255
Length: 503, dtype: int64

In [17]:
for ticker in ["FRT", "PHM", "SYY"]:
    count = (df["Ticker"] == ticker).sum()
    print(f"{ticker}: {count} rows")

FRT: 1255 rows
PHM: 1255 rows
SYY: 1255 rows

In [18]:
df[df["Adj Close"].notna()]

Empty DataFrame
Columns: [Date, Ticker, Open, High, Low, Close, Volume, Adj Close]
Index: []

In [19]:
df=df.drop(columns=['Adj Close'])

df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2021-06-21,VRSN,220.366970,222.366633,218.574160,221.381577,511300.0
1,2021-06-21,BF-B,65.870773,66.372575,65.548184,66.336731,783000.0
2,2021-06-21,MSI,196.559049,200.433110,195.399663,199.179459,746300.0
3,2021-06-21,WSM,69.193813,71.281085,69.121053,70.658089,1887400.0
4,2021-06-21,MET,50.399791,51.361588,50.399791,51.249950,6101100.0
...,...,...,...,...,...,...,...
631260,2026-06-18,COST,962.700012,964.000000,948.309998,951.450012,3742900.0
631261,2026-06-18,FISV,48.570000,48.950001,47.500000,47.860001,13540200.0
631262,2026-06-18,EQIX,1104.500000,1114.599976,1088.619995,1092.189941,807800.0
631263,2026-06-18,EXPE,242.050003,243.759995,238.850006,240.899994,3024200.0
631264,2026-06-18,GM,80.610001,80.949997,78.940002,79.290001,18900900.0

In [20]:
df.columns.name = None
df

,Date,Ticker,Open,High,Low,Close,Volume
0,2021-06-21,VRSN,220.366970,222.366633,218.574160,221.381577,511300.0
1,2021-06-21,BF-B,65.870773,66.372575,65.548184,66.336731,783000.0
2,2021-06-21,MSI,196.559049,200.433110,195.399663,199.179459,746300.0
3,2021-06-21,WSM,69.193813,71.281085,69.121053,70.658089,1887400.0
4,2021-06-21,MET,50.399791,51.361588,50.399791,51.249950,6101100.0
...,...,...,...,...,...,...,...
631260,2026-06-18,COST,962.700012,964.000000,948.309998,951.450012,3742900.0
631261,2026-06-18,FISV,48.570000,48.950001,47.500000,47.860001,13540200.0
631262,2026-06-18,EQIX,1104.500000,1114.599976,1088.619995,1092.189941,807800.0
631263,2026-06-18,EXPE,242.050003,243.759995,238.850006,240.899994,3024200.0
631264,2026-06-18,GM,80.610001,80.949997,78.940002,79.290001,18900900.0

In [12]:
test = yf.download(["BRK-B","BF-B"], period="5d")
print(test)

[*********************100%***********************]  2 of 2 completed

Price           Close                   High                    Low  \
Ticker           BF-B       BRK-B       BF-B       BRK-B       BF-B
Date
2026-06-12  27.010000  489.250000  27.080000  489.989990  26.450001
2026-06-15  26.940001  495.519989  27.360001  497.109985  26.879999
2026-06-16  26.610001  494.950012  27.230000  499.790009  26.469999
2026-06-17  25.510000  491.279999  26.580000  494.769989  25.270000
2026-06-18  26.639999  489.459991  26.850000  493.570007  25.610001

Price                        Open               Volume
Ticker           BRK-B       BF-B       BRK-B     BF-B    BRK-B
Date
2026-06-12  484.510010  26.709999  486.670013  2186600  4591300
2026-06-15  487.559998  26.940001  487.559998  2981100  6253600
2026-06-16  492.429993  27.030001  497.000000  2147000  4345900
2026-06-17  487.899994  26.480000  493.239990  3038200  5412000
2026-06-18  485.769989  25.879999  492.750000  7148100  8882300

In [13]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [14]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [15]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [16]:
test = yf.download("FDS", period="5d")
print(test)

test2 = yf.download("MS", period="5d")
print(test2)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker             FDS         FDS         FDS         FDS      FDS
Date
2026-06-12  241.160004  243.240005  231.149994  237.000000  2059000
2026-06-15  235.860001  247.080002  234.660004  238.740005   579200
2026-06-16  237.559998  241.740005  235.009995  237.770004   562600
2026-06-17  228.300003  240.570007  228.300003  234.860001   648900
2026-06-18  221.289993  223.990005  216.559998  218.679993  1732900

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker              MS          MS          MS          MS        MS
Date
2026-06-12  214.039993  217.619995  212.660004  215.050003   4694300
2026-06-15  217.979996  220.600006  216.850006  218.759995   5862500
2026-06-16  220.830002  222.300003  218.589996  220.509995   5091700
2026-06-17  224.960007  228.070007  221.360001  222.110001   8689700
2026-06-18  223.169998  230.470001  222.889999  229.089996  11933200

In [22]:
df.to_csv('backfill_data_2106.csv')

In [25]:
ohlcv_cols = ["Open", "High", "Low", "Close", "Volume"]

null_summary = (
    df[df["Ticker"].isin(["FRT", "PHM", "SYY", "GOOG", "BF-B"])]
    .groupby("Ticker")[ohlcv_cols]
    .apply(lambda x: x.isna().sum())
)
print(null_summary)

        Open  High   Low  Close  Volume
Ticker
BF-B       0     0     0      0       0
FRT     1255  1255  1255   1255    1255
GOOG       0     0     0      0       0
PHM     1255  1255  1255   1255    1255
SYY     1255  1255  1255   1255    1255