In [6]:
import yfinance as yf

In [7]:
# list of ticker symbols for download (Needs to be done for S&P 1500)
tickerStrings = ['AAPL', 'MSFT']

In [15]:
df = yf.download(tickerStrings, group_by='Ticker', period='1mo')

[*********************100%***********************]  2 of 2 completed

In [16]:
df

Ticker            MSFT                                                \
Price             Open        High         Low       Close    Volume
Date
2026-05-19  428.970892  431.764859  415.589870  416.517883  33018700
2026-05-20  413.274901  421.187755  410.411078  420.149994  27864000
2026-05-21  424.750000  426.339996  415.709991  419.089996  31393500
2026-05-22  419.540009  424.399994  416.329987  418.570007  22390300
2026-05-26  416.429993  419.769989  413.019989  416.029999  30398000
2026-05-27  411.010010  415.940002  409.579987  412.670013  28901500
2026-05-28  412.980011  429.489990  412.670013  426.989990  47250500
2026-05-29  432.549988  450.329987  432.359985  450.239990  79654400
2026-06-01  464.839996  466.320007  458.269989  460.519989  53628900
2026-06-02  446.880005  453.500000  440.429993  441.309998  37036800
2026-06-03  438.450012  440.390015  424.250000  427.339996  39037000
2026-06-04  435.809998  436.149994  426.410004  428.049988  26899500
2026-06-05  428.339996  429.470001  414.399994  416.670013  34782200
2026-06-08  414.140015  417.160004  408.559998  411.739990  32086700
2026-06-09  409.029999  411.980011  398.480011  403.410004  35317300
2026-06-10  398.549988  405.040009  397.160004  397.359985  32576000
2026-06-11  395.209991  396.850006  384.000000  390.339996  47224100
2026-06-12  391.429993  391.739990  382.269989  390.739990  34865800
2026-06-15  396.799988  401.750000  392.850006  399.760010  32266400
2026-06-16  395.790009  396.839996  390.690002  393.829987  31506800
2026-06-17  390.250000  390.369995  377.320007  378.910004  41987800
2026-06-18         NaN         NaN         NaN         NaN  58466440

Ticker            AAPL
Price             Open        High         Low       Close    Volume
Date
2026-05-19  296.970001  300.510010  296.350006  298.970001  42243600
2026-05-20  298.179993  302.799988  298.079987  302.250000  38229800
2026-05-21  301.059998  305.540009  300.399994  304.989990  42965100
2026-05-22  306.119995  311.399994  305.839996  308.820007  43670200
2026-05-26  309.559998  311.820007  307.670013  308.329987  48000500
2026-05-27  308.329987  313.260010  308.299988  310.850006  50430900
2026-05-28  310.679993  312.799988  309.570007  312.510010  48220400
2026-05-29  311.779999  315.000000  309.529999  312.059998  70026800
2026-06-01  309.630005  310.940002  305.019989  306.309998  48849900
2026-06-02  307.459991  315.450012  306.690002  315.200012  44534700
2026-06-03  314.179993  316.940002  308.850006  310.260010  50836700
2026-06-04  313.230011  313.540009  309.649994  311.230011  44869100
2026-06-05  312.859985  315.170013  307.149994  307.339996  65310500
2026-06-08  308.739990  317.399994  301.170013  301.540009  77949100
2026-06-09  300.279999  300.750000  287.779999  290.549988  70108800
2026-06-10  290.739990  294.750000  287.380005  291.579987  52793300
2026-06-11  293.720001  297.000000  289.589996  295.630005  42572500
2026-06-12  296.029999  297.140015  289.619995  291.130005  38742100
2026-06-15  294.119995  297.779999  291.700012  296.420013  45732600
2026-06-16  295.250000  300.480011  293.970001  299.239990  39874400
2026-06-17  300.850006  302.070007  294.359985  295.950012  42745100
2026-06-18         NaN         NaN         NaN         NaN  76701676

In [17]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2026-05-19,MSFT,428.970892,431.764859,415.589870,416.517883,33018700
1,2026-05-19,AAPL,296.970001,300.510010,296.350006,298.970001,42243600
2,2026-05-20,MSFT,413.274901,421.187755,410.411078,420.149994,27864000
3,2026-05-20,AAPL,298.179993,302.799988,298.079987,302.250000,38229800
4,2026-05-21,MSFT,424.750000,426.339996,415.709991,419.089996,31393500
5,2026-05-21,AAPL,301.059998,305.540009,300.399994,304.989990,42965100
6,2026-05-22,MSFT,419.540009,424.399994,416.329987,418.570007,22390300
7,2026-05-22,AAPL,306.119995,311.399994,305.839996,308.820007,43670200
8,2026-05-26,MSFT,416.429993,419.769989,413.019989,416.029999,30398000
9,2026-05-26,AAPL,309.559998,311.820007,307.670013,308.329987,48000500
10,2026-05-27,MSFT,411.010010,415.940002,409.579987,412.670013,28901500
11,2026-05-27,AAPL,308.329987,313.260010,308.299988,310.850006,50430900
12,2026-05-28,MSFT,412.980011,429.489990,412.670013,426.989990,47250500
13,2026-05-28,AAPL,310.679993,312.799988,309.570007,312.510010,48220400
14,2026-05-29,MSFT,432.549988,450.329987,432.359985,450.239990,79654400
15,2026-05-29,AAPL,311.779999,315.000000,309.529999,312.059998,70026800
16,2026-06-01,MSFT,464.839996,466.320007,458.269989,460.519989,53628900
17,2026-06-01,AAPL,309.630005,310.940002,305.019989,306.309998,48849900
18,2026-06-02,MSFT,446.880005,453.500000,440.429993,441.309998,37036800
19,2026-06-02,AAPL,307.459991,315.450012,306.690002,315.200012,44534700
20,2026-06-03,MSFT,438.450012,440.390015,424.250000,427.339996,39037000
21,2026-06-03,AAPL,314.179993,316.940002,308.850006,310.260010,50836700
22,2026-06-04,MSFT,435.809998,436.149994,426.410004,428.049988,26899500
23,2026-06-04,AAPL,313.230011,313.540009,309.649994,311.230011,44869100
24,2026-06-05,MSFT,428.339996,429.470001,414.399994,416.670013,34782200
25,2026-06-05,AAPL,312.859985,315.170013,307.149994,307.339996,65310500
26,2026-06-08,MSFT,414.140015,417.160004,408.559998,411.739990,32086700
27,2026-06-08,AAPL,308.739990,317.399994,301.170013,301.540009,77949100
28,2026-06-09,MSFT,409.029999,411.980011,398.480011,403.410004,35317300
29,2026-06-09,AAPL,300.279999,300.750000,287.779999,290.549988,70108800
30,2026-06-10,MSFT,398.549988,405.040009,397.160004,397.359985,32576000
31,2026-06-10,AAPL,290.739990,294.750000,287.380005,291.579987,52793300
32,2026-06-11,MSFT,395.209991,396.850006,384.000000,390.339996,47224100
33,2026-06-11,AAPL,293.720001,297.000000,289.589996,295.630005,42572500
34,2026-06-12,MSFT,391.429993,391.739990,382.269989,390.739990,34865800
35,2026-06-12,AAPL,296.029999,297.140015,289.619995,291.130005,38742100
36,2026-06-15,MSFT,396.799988,401.750000,392.850006,399.760010,32266400
37,2026-06-15,AAPL,294.119995,297.779999,291.700012,296.420013,45732600
38,2026-06-16,MSFT,395.790009,396.839996,390.690002,393.829987,31506800
39,2026-06-16,AAPL,295.250000,300.480011,293.970001,299.239990,39874400
40,2026-06-17,MSFT,390.250000,390.369995,377.320007,378.910004,41987800
41,2026-06-17,AAPL,300.850006,302.070007,294.359985,295.950012,42745100
42,2026-06-18,MSFT,NaN,NaN,NaN,NaN,58466440
43,2026-06-18,AAPL,NaN,NaN,NaN,NaN,76701676