In [1]:
pip install yfinance lxml requests pandas

Requirement already satisfied: yfinance in ./.venv/lib/python3.12/site-packages (1.4.1)
Requirement already satisfied: lxml in ./.venv/lib/python3.12/site-packages (6.1.1)
Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in ./.venv/lib/python3.12/site-packages (from yfinance) (2.4.6)
Requirement already satisfied: multitasking>=0.0.7 in ./.venv/lib/python3.12/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in ./.venv/lib/python3.12/site-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in ./.venv/lib/python3.12/site-packages (from yfinance) (2026.2)
Requirement already satisfied: peewee>=3.16.2 in ./.venv/lib/python3.12/site-packages (from yfinance) (4.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./.venv/lib/python3.12/site-packages (from yfinance) (4.15.0)
Requirement already satisfied: curl_cffi>=0.15 in ./.venv/lib/python3.12/site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in ./.venv/lib/python3.12/site-packages (from yfinance) (7.35.1)
Requirement already satisfied: websockets>=13.0 in ./.venv/lib/python3.12/site-packages (from yfinance) (16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: rich in ./.venv/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (15.0.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.12/site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import lxml
import requests
import yfinance as yf
from io import StringIO

In [3]:
url= "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [4]:
response=requests.get(url, headers=headers)

sp500=pd.read_html(StringIO(response.text))[0]
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [5]:
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [6]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [7]:
# list of ticker symbols for download (Needs to be done for S&P 500)
tickerStrings = sp500['Symbol'].tolist()

In [8]:
df = yf.download(tickerStrings, group_by='Ticker', period='1d')

[******                12%                       ]  60 of 503 completed$BRK-B: possibly delisted; no price data found  (period=1d)
[*********************100%***********************]  503 of 503 completed

1 Failed download:
['BRK-B']: possibly delisted; no price data found  (period=1d)

In [9]:
df

Ticker       APTV                                           AEE              \
Price        Open       High    Low  Close   Volume        Open        High
Date
2026-06-18  63.77  64.860001  62.93  63.68  5457100  109.110001  110.089996

Ticker                                       ...    KEY                      \
Price              Low       Close   Volume  ...   Open  High    Low  Close
Date                                         ...
2026-06-18  108.169998  108.669998  2403600  ...  22.84  22.9  22.51  22.59

Ticker                      REG
Price         Volume       Open       High        Low      Close   Volume
Date
2026-06-18  17219200  77.830002  77.830002  76.690002  76.879997  1669600

[1 rows x 2516 columns]

In [10]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-06-18,APTV,63.770000,64.860001,62.930000,63.680000,5457100.0,NaN
1,2026-06-18,AEE,109.110001,110.089996,108.169998,108.669998,2403600.0,NaN
2,2026-06-18,TPL,354.510010,359.250000,351.809998,355.109985,994900.0,NaN
3,2026-06-18,UNP,258.079987,263.679993,256.119995,256.880005,3443000.0,NaN
4,2026-06-18,EME,846.630005,849.669983,833.119995,836.590027,1132500.0,NaN
...,...,...,...,...,...,...,...,...
498,2026-06-18,MAA,134.360001,134.869995,131.839996,132.500000,1686200.0,NaN
499,2026-06-18,RMD,188.919998,190.360001,187.009995,188.630005,3884900.0,NaN
500,2026-06-18,WDC,764.150024,799.869995,739.109985,746.229980,16683900.0,NaN
501,2026-06-18,KEY,22.840000,22.900000,22.510000,22.590000,17219200.0,NaN
502,2026-06-18,REG,77.830002,77.830002,76.690002,76.879997,1669600.0,NaN

In [11]:
df.columns.name = None
df

,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-06-18,APTV,63.770000,64.860001,62.930000,63.680000,5457100.0,NaN
1,2026-06-18,AEE,109.110001,110.089996,108.169998,108.669998,2403600.0,NaN
2,2026-06-18,TPL,354.510010,359.250000,351.809998,355.109985,994900.0,NaN
3,2026-06-18,UNP,258.079987,263.679993,256.119995,256.880005,3443000.0,NaN
4,2026-06-18,EME,846.630005,849.669983,833.119995,836.590027,1132500.0,NaN
...,...,...,...,...,...,...,...,...
498,2026-06-18,MAA,134.360001,134.869995,131.839996,132.500000,1686200.0,NaN
499,2026-06-18,RMD,188.919998,190.360001,187.009995,188.630005,3884900.0,NaN
500,2026-06-18,WDC,764.150024,799.869995,739.109985,746.229980,16683900.0,NaN
501,2026-06-18,KEY,22.840000,22.900000,22.510000,22.590000,17219200.0,NaN
502,2026-06-18,REG,77.830002,77.830002,76.690002,76.879997,1669600.0,NaN

In [12]:
test = yf.download(["BRK-B","BF-B"], period="5d")
print(test)

[*********************100%***********************]  2 of 2 completed

Price           Close                   High                    Low  \
Ticker           BF-B       BRK-B       BF-B       BRK-B       BF-B
Date
2026-06-12  27.010000  489.250000  27.080000  489.989990  26.450001
2026-06-15  26.940001  495.519989  27.360001  497.109985  26.879999
2026-06-16  26.610001  494.950012  27.230000  499.790009  26.469999
2026-06-17  25.510000  491.279999  26.580000  494.769989  25.270000
2026-06-18  26.639999  489.459991  26.850000  493.570007  25.610001

Price                        Open               Volume
Ticker           BRK-B       BF-B       BRK-B     BF-B    BRK-B
Date
2026-06-12  484.510010  26.709999  486.670013  2186600  4591300
2026-06-15  487.559998  26.940001  487.559998  2981100  6253600
2026-06-16  492.429993  27.030001  497.000000  2147000  4345900
2026-06-17  487.899994  26.480000  493.239990  3038200  5412000
2026-06-18  485.769989  25.879999  492.750000  7148100  8882300

In [13]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [14]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [15]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [16]:
test = yf.download("FDS", period="5d")
print(test)

test2 = yf.download("MS", period="5d")
print(test2)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker             FDS         FDS         FDS         FDS      FDS
Date
2026-06-12  241.160004  243.240005  231.149994  237.000000  2059000
2026-06-15  235.860001  247.080002  234.660004  238.740005   579200
2026-06-16  237.559998  241.740005  235.009995  237.770004   562600
2026-06-17  228.300003  240.570007  228.300003  234.860001   648900
2026-06-18  221.289993  223.990005  216.559998  218.679993  1732900

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker              MS          MS          MS          MS        MS
Date
2026-06-12  214.039993  217.619995  212.660004  215.050003   4694300
2026-06-15  217.979996  220.600006  216.850006  218.759995   5862500
2026-06-16  220.830002  222.300003  218.589996  220.509995   5091700
2026-06-17  224.960007  228.070007  221.360001  222.110001   8689700
2026-06-18  223.169998  230.470001  222.889999  229.089996  11933200