In [34]:
pip install lxml

Requirement already satisfied: lxml in ./.venv/lib/python3.12/site-packages (6.1.1)
Note: you may need to restart the kernel to use updated packages.

In [35]:
pip install requests

Requirement already satisfied: requests in ./.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests) (2026.6.17)
Note: you may need to restart the kernel to use updated packages.

In [36]:
pip install io

ERROR: Could not find a version that satisfies the requirement io (from versions: none)
ERROR: No matching distribution found for io
Note: you may need to restart the kernel to use updated packages.

In [37]:
import pandas as pd
import lxml
import requests

In [38]:
import yfinance as yf

In [39]:
url= "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers= {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

In [40]:
response=requests.get(url, headers=headers)

sp500=pd.read_html(StringIO(response.text))[0]
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [43]:
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Symbol                 503 non-null    str
 1   Security               503 non-null    str
 2   GICS Sector            503 non-null    str
 3   GICS Sub-Industry      503 non-null    str
 4   Headquarters Location  503 non-null    str
 5   Date added             503 non-null    str
 6   CIK                    503 non-null    int64
 7   Founded                503 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [56]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [57]:
# list of ticker symbols for download (Needs to be done for S&P 500)
tickerStrings = sp500['Symbol'].tolist()

In [62]:
df = yf.download(tickerStrings, group_by='Ticker', period='5d')

[                       1%                       ]  4 of 503 completed

KeyboardInterrupt:

In [46]:
df

Ticker             TYL                                               \
Price             Open        High         Low       Close   Volume
Date
2026-05-19  328.420013  330.920013  318.429993  322.739990  1005200
2026-05-20  316.600006  317.959991  310.149994  317.260010   622600
2026-05-21  313.290009  313.290009  305.000000  308.739990   514400
2026-05-22  309.700012  316.820007  309.529999  313.250000   357900
2026-05-26  309.329987  311.630005  305.750000  307.390015   650100
2026-05-27  306.000000  310.630005  299.829987  302.549988   626900
2026-05-28  303.880005  310.540009  301.160004  306.040009   654500
2026-05-29  305.619995  313.260010  302.470001  313.149994  1217400
2026-06-01  321.890015  331.540009  317.309998  329.829987   780900
2026-06-02  321.690002  322.500000  307.140015  313.559998   645100
2026-06-03  310.010010  310.600006  298.950012  303.769989   653600
2026-06-04  310.850006  314.559998  306.170013  308.149994   691700
2026-06-05  312.989990  316.010010  305.170013  312.070007   658100
2026-06-08  307.329987  308.850006  301.160004  303.769989   640200
2026-06-09  297.230011  309.010010  293.720001  308.920013  1394100
2026-06-10  311.880005  314.709991  302.589996  302.809998  1645400
2026-06-11  297.829987  305.660004  294.079987  295.480011  1204000
2026-06-12  292.910004  298.899994  285.859985  298.839996   712800
2026-06-15  298.119995  300.000000  286.010010  289.839996   782400
2026-06-16  290.040009  300.089996  288.660004  298.269989  1127200
2026-06-17  295.049988  301.000000  287.299988  287.709991   739300
2026-06-18         NaN         NaN         NaN         NaN   813446

Ticker            FLEX                                                ...  \
Price             Open        High         Low       Close    Volume  ...
Date                                                                  ...
2026-05-19  125.410004  128.389999  121.300003  126.290001   6182200  ...
2026-05-20  127.760002  134.000000  127.089996  131.520004   6316300  ...
2026-05-21  130.410004  134.750000  129.160004  131.070007   4826700  ...
2026-05-22  132.759995  134.259995  128.580002  132.470001   3583200  ...
2026-05-26  135.929993  144.850006  135.929993  143.240005   5453500  ...
2026-05-27  145.399994  146.149994  139.179993  145.789993   5445900  ...
2026-05-28  145.250000  147.759995  139.910004  144.850006   4983200  ...
2026-05-29  146.520004  154.250000  146.050003  150.779999  11420200  ...
2026-06-01  149.630005  151.160004  145.509995  148.009995   4588900  ...
2026-06-02  150.470001  159.860001  149.369995  159.429993   5526000  ...
2026-06-03  161.750000  166.860001  160.000000  161.940002   6634300  ...
2026-06-04  156.479996  161.110001  150.860001  159.509995   5257700  ...
2026-06-05  155.250000  157.410004  149.300003  151.919998   5485900  ...
2026-06-08  158.699997  158.699997  149.740005  150.830002   6593900  ...
2026-06-09  154.399994  156.529999  139.669998  147.210007   4978900  ...
2026-06-10  144.679993  149.449997  137.779999  139.490005   4493000  ...
2026-06-11  141.500000  152.130005  141.350006  151.990005   3303900  ...
2026-06-12  149.669998  152.520004  148.360001  149.710007   5115000  ...
2026-06-15  154.839996  155.699997  145.320007  149.220001   4655900  ...
2026-06-16  149.449997  149.809998  142.179993  146.929993   5929000  ...
2026-06-17  149.979996  150.339996  141.110001  143.130005   7336300  ...
2026-06-18  147.020004  153.380005  143.850006  147.610001  80915300  ...

Ticker           KVUE                                                   HPE  \
Price            Open       High        Low      Close    Volume       Open
Date
2026-05-19  17.200001  17.389999  17.040001  17.150000  18907900  32.355339
2026-05-20  17.150000  17.389999  17.065001  17.320000  16569300  32.724260
2026-05-21  17.245001  17.549999  17.049999  17.459999  22001100  33.297583
2026-05-22  17.469999  17.629999  17.465000  17.530001  13689600  34.548922
2026-05-26  17.530001  17.625999  17.490000  17.490000  14081000  37.809380
2026-05-27  17.610001  17.989000  17.570000  17.690001  25384300  37.699701
2026-05-28  17.590000  17.760000  17.565001  17.639999  12171300  37.360694
2026-05-29  17.620001  17.684999  17.240000  17.280001  33794100  42.655204
2026-06-01  17.290001  17.485001  17.254999  17.350000  18663700  44.051119
2026-06-02  17.340000  17.480000  17.150000  17.320000  18528200  62.876044
2026-06-03  17.320000  17.340000  16.820000  16.830000  38337500  54.021949
2026-06-04  17.030001  17.190001  16.665001  16.879999  26035900  52.845389
2026-06-05  17.010000  17.770000  16.950001  17.709999  24620500  52.750667
2026-06-08  17.650000  17.750000  17.480000  17.549999  20218000  49.804286
2026-06-09  17.620001  17.940001  17.440001  17.920000  18133400  49.689622
2026-06-10  18.000000  18.129999  17.850000  18.049999  12624800  47.710412
2026-06-11  18.110001  18.209999  18.000000  18.070000  14108900  44.868727
2026-06-12  18.160000  18.260000  18.000000  18.139999  14702600  46.374319
2026-06-15  18.080000  18.385000  18.080000  18.250000  11515300  49.330670
2026-06-16  18.285000  18.510000  18.250000  18.430000  11506100  49.134998
2026-06-17  18.450001  18.530001  17.980000  18.010000  18315000  49.500000
2026-06-18        NaN        NaN        NaN        NaN  32064947  49.174999

Ticker
Price            High        Low      Close     Volume
Date
2026-05-19  32.943618  31.787000  32.524841   10241000
2026-05-20  33.900818  32.594638  33.701401   11467600
2026-05-21  33.890849  33.018401  33.870907   11649800
2026-05-22  37.634891  34.399358  37.470375   30722400
2026-05-26  38.467458  37.221105  37.948975   16802000
2026-05-27  37.789439  36.602908  37.091480   17674600
2026-05-28  38.243111  36.468305  38.098534   23279900
2026-05-29  44.444970  41.398881  42.914448   86121400
2026-06-01  47.830064  43.273396  46.862892  115597800
2026-06-02  64.062572  53.314020  55.986202  153197800
2026-06-03  55.826670  52.456529  54.989120   56953400
2026-06-04  54.311102  52.167372  53.533375   36790300
2026-06-05  52.899234  48.398402  49.056477   37733400
2026-06-08  50.717614  48.772306  49.724518   28878300
2026-06-09  50.352683  45.596597  48.129189   28578500
2026-06-10  47.830065  44.778990  45.357300   33229400
2026-06-11  46.663475  44.609487  46.663475   24482800
2026-06-12  49.634780  45.835897  48.029476   23521900
2026-06-15  49.455305  47.959681  48.876999   30500700
2026-06-16  50.340000  47.980000  48.380001   24311600
2026-06-17  50.450001  47.952000  48.200001   31243800
2026-06-18  49.599998  46.930000  47.410000   53337800

[22 rows x 2517 columns]

In [47]:
df = df.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index()
df

Price,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-05-19,TYL,328.420013,330.920013,318.429993,322.739990,1005200.0,NaN
1,2026-05-19,FLEX,125.410004,128.389999,121.300003,126.290001,6182200.0,NaN
2,2026-05-19,KHC,22.949067,23.165150,22.595475,22.865582,13737200.0,NaN
3,2026-05-19,DELL,234.250000,239.750000,227.270004,235.259995,4082700.0,NaN
4,2026-05-19,GNRC,247.669998,248.750000,238.179993,243.970001,944200.0,NaN
...,...,...,...,...,...,...,...,...
11061,2026-06-18,MAR,NaN,NaN,NaN,NaN,2232712.0,NaN
11062,2026-06-18,EG,NaN,NaN,NaN,NaN,370920.0,NaN
11063,2026-06-18,MPWR,1529.239990,1581.040039,1515.619995,1563.699951,1935600.0,NaN
11064,2026-06-18,KVUE,NaN,NaN,NaN,NaN,32064947.0,NaN
11065,2026-06-18,HPE,49.174999,49.599998,46.930000,47.410000,53337800.0,NaN

In [48]:
df.columns.name = None
df

,Date,Ticker,Open,High,Low,Close,Volume,Adj Close
0,2026-05-19,TYL,328.420013,330.920013,318.429993,322.739990,1005200.0,NaN
1,2026-05-19,FLEX,125.410004,128.389999,121.300003,126.290001,6182200.0,NaN
2,2026-05-19,KHC,22.949067,23.165150,22.595475,22.865582,13737200.0,NaN
3,2026-05-19,DELL,234.250000,239.750000,227.270004,235.259995,4082700.0,NaN
4,2026-05-19,GNRC,247.669998,248.750000,238.179993,243.970001,944200.0,NaN
...,...,...,...,...,...,...,...,...
11061,2026-06-18,MAR,NaN,NaN,NaN,NaN,2232712.0,NaN
11062,2026-06-18,EG,NaN,NaN,NaN,NaN,370920.0,NaN
11063,2026-06-18,MPWR,1529.239990,1581.040039,1515.619995,1563.699951,1935600.0,NaN
11064,2026-06-18,KVUE,NaN,NaN,NaN,NaN,32064947.0,NaN
11065,2026-06-18,HPE,49.174999,49.599998,46.930000,47.410000,53337800.0,NaN

In [49]:
test = yf.download(["BRK-B","BF-B"], period="5d")
print(test)

[*********************100%***********************]  1 of 2 completed

Price           Close                   High                    Low  \
Ticker           BF-B       BRK-B       BF-B       BRK-B       BF-B
Date
2026-06-12  27.010000  489.250000  27.080000  489.989990  26.450001
2026-06-15  26.940001  495.519989  27.360001  497.109985  26.879999
2026-06-16  26.610001  494.950012  27.230000  499.790009  26.469999
2026-06-17  25.510000  491.279999  26.580000  494.769989  25.270000
2026-06-18        NaN  489.459991        NaN  493.570007        NaN

Price                        Open               Volume
Ticker           BRK-B       BF-B       BRK-B     BF-B    BRK-B
Date
2026-06-12  484.510010  26.709999  486.670013  2186600  4591300
2026-06-15  487.559998  26.940001  487.559998  2981100  6253600
2026-06-16  492.429993  27.030001  497.000000  2147000  4345900
2026-06-17  487.899994  26.480000  493.239990  3038200  5412000
2026-06-18  485.769989        NaN  492.750000  7147447  8882300

In [50]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

['BRK.B', 'BF.B']

In [54]:
sp500['Symbol']=sp500['Symbol'].str.replace(".", "-", regex=False)

In [55]:
dotted = sp500.loc[sp500["Symbol"].str.contains(".", regex=False), "Symbol"]
print(dotted.tolist())

[]

In [59]:
test = yf.download("EXPE", period="5d")
print(test)

test2 = yf.download("CNC", period="5d")
print(test2)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open   Volume
Ticker            EXPE        EXPE        EXPE        EXPE     EXPE
Date
2026-06-12  224.889999  229.740005  220.490005  226.350006  1257400
2026-06-15  236.979996  239.490005  229.229996  229.899994  1675300
2026-06-16  243.559998  246.500000  237.089996  237.089996  1778900
2026-06-17  239.470001  244.360001  238.809998  241.880005  1174300
2026-06-18         NaN         NaN         NaN         NaN  2771206

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open    Volume
Ticker            CNC        CNC        CNC        CNC       CNC
Date
2026-06-12  65.190002  65.910004  63.270000  64.190002   4784300
2026-06-15  63.400002  65.110001  62.209999  64.620003   6468500
2026-06-16  61.389999  63.880001  60.529999  63.230000   6162900
2026-06-17  60.639999  62.410000  59.900002  61.480000   5710700
2026-06-18        NaN        NaN        NaN        NaN  11087188